// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDLgWkGa3SRr54z2NiisX0twQLNVAaTT8',
    appId: '1:902115810519:web:489f00711c3dd265dce492',
    messagingSenderId: '902115810519',
    projectId: 'hotelio-ea91f',
    authDomain: 'hotelio-ea91f.firebaseapp.com',
    storageBucket: 'hotelio-ea91f.firebasestorage.app',
    measurementId: 'G-X8KY1L35N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxrhlzOQ0yqbt7E7UYH1SH8yrqXOgvSrw',
    appId: '1:902115810519:android:b49d3cdeb738d308dce492',
    messagingSenderId: '902115810519',
    projectId: 'hotelio-ea91f',
    storageBucket: 'hotelio-ea91f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkF4nnx6O7GSR0E9NexuCGpTzX3m9OWGk',
    appId: '1:902115810519:ios:bb78739f291b1628dce492',
    messagingSenderId: '902115810519',
    projectId: 'hotelio-ea91f',
    storageBucket: 'hotelio-ea91f.firebasestorage.app',
    androidClientId: '902115810519-ingbvpla4441c16nkedg5oimv8pq1jfr.apps.googleusercontent.com',
    iosClientId: '902115810519-jcd390aoppgpajelgq9ia1v9uk52gbu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.projekMopro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkF4nnx6O7GSR0E9NexuCGpTzX3m9OWGk',
    appId: '1:902115810519:ios:bb78739f291b1628dce492',
    messagingSenderId: '902115810519',
    projectId: 'hotelio-ea91f',
    storageBucket: 'hotelio-ea91f.firebasestorage.app',
    androidClientId: '902115810519-ingbvpla4441c16nkedg5oimv8pq1jfr.apps.googleusercontent.com',
    iosClientId: '902115810519-jcd390aoppgpajelgq9ia1v9uk52gbu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.projekMopro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDLgWkGa3SRr54z2NiisX0twQLNVAaTT8',
    appId: '1:902115810519:web:e3d8a073b3c738abdce492',
    messagingSenderId: '902115810519',
    projectId: 'hotelio-ea91f',
    authDomain: 'hotelio-ea91f.firebaseapp.com',
    storageBucket: 'hotelio-ea91f.firebasestorage.app',
    measurementId: 'G-CBD3Z7V0V6',
  );
}
